export const iconList=
    ['Accessibility',  'Activity', 'AirVent', 'Airplay',
 'AlarmClockOff', 'AlarmClock',  'Album', 
 'AlignCenterHorizontal',
 'AlignCenterVertical', 'AlignCenter', 'AlignEndHorizontal', 'AlignEndVertical',
 'AlignHorizontalDistributeCenter', 'AlignHorizontalDistributeEnd', 
 'AlignHorizontalDistributeStart', 'AlignHorizontalJustifyCenter', 
 'AlignHorizontalJustifyEnd', 'AlignHorizontalJustifyStart', 
 'AlignHorizontalSpaceAround', 'AlignHorizontalSpaceBetween', 
 'AlignJustify', 'AlignLeft', 'AlignRight', 'AlignStartHorizontal',
 'AlignStartVertical', 'AlignVerticalDistributeCenter', 'AlignVerticalDistributeEnd', 
 'AlignVerticalDistributeStart', 'AlignVerticalJustifyCenter', 
 'AlignVerticalJustifyEnd', 'AlignVerticalJustifyStart', 
 'AlignVerticalSpaceAround', 'AlignVerticalSpaceBetween',
 'Ampersand', 'Ampersands', 'Anchor', 'Angry', 'Annoyed',
 'Antenna', 'Aperture', 'AppWindow', 'Apple', 'ArchiveRestore',
 'ArchiveX', 'Archive', 'AreaChart',  'ArrowBigDownDash', 
 'ArrowBigDown', 'ArrowBigLeftDash', 'ArrowBigLeft', 'ArrowBigRightDash',
 'ArrowBigRight', 'ArrowBigUpDash', 'ArrowBigUp', 'ArrowDown01',
 'ArrowDown10', 'ArrowDownAZ', , 'ArrowDownFromLine',
  'ArrowDownLeft',
 'ArrowDownNarrowWide',  'ArrowDownRightSquare',
 'ArrowDownRight', 'ArrowDownToDot', 'ArrowDownToLine',
 'ArrowDownUp', 'ArrowDownWideNarrow', 'ArrowDownZA', 'ArrowDown', 'ArrowLeftFromLine', 'ArrowLeftRight', 
 'ArrowLeftToLine', 'ArrowLeft',  
  'ArrowRightToLine', 'ArrowRight', 'ArrowUp01',
 'ArrowUp10', 'ArrowUpAZ', 'ArrowUpDown', 'ArrowUpFromDot',
 'ArrowUpFromLine', 'ArrowUpLeft',
 'ArrowUpNarrowWide', 'ArrowUpRight',
   'ArrowUpWideNarrow', 'ArrowUpZA', 'ArrowUp',
 'ArrowsUpFromLine', 'Asterisk', 'AtSign', 'Atom', 'Award', 'Axe', 'Axis3d']